[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "TheWeavers"
name = "LethalBestiary"
description = "Personal modding tools for Lethal Company"
websiteUrl = "https://github.com/FelixAllard/Xilef-LethalBestiary-LC"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Evaisa-HookGenPatcher = "0.0.5"

[build]
icon = "icons/lethal-lib.png"
readme = "../../README.md"
outdir = "../dist"

[[build.copy]]
source = "../bin/Release/netstandard2.1/LethalBestiary.dll"
target = "plugins/LethalLib/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "libraries", "tools", "mods", "bepinex", ]


